- name: data types
  host: local
  connection: local
  vars:
   course: "dev ops with aws"
   douration: 120
   is_live: true
   toos: # ["linux", "shell", "ansible ", "aws"]
    - "linux"
    - "shell"
    - "ansible"
    - "aws"
  concepts: #dictionary or map
    clous: aws
    pm: ansible
    os: linux
    tasks:
     - name: print course info
       ansible.builtin.debug:
        msg: "course name is :  {{course}} and duration is {{douration}} hours tools are {{tools}} concepts are: {{concepts}}" 


