- name: functions
  hosts: local
  connection: local

  vars:
    technologies: devops, linux, windows, shell, ansible # string

  tasks:
   - name: default variable
     ansible.builtin.debug:
      msg: "hello, {{name | default('pagadala')}}"

 #string to list
   - name: convert string to list
     ansible.builtin.debug:
      msg: "technologies are: {{ technologies | split(', ') }}"     