- name: PLAY-01
  hosts: frontend
  tasks:
  - name: PLAY-01 and TASK-01
    ansible.builtin.debug:
     msg: "hello from PLAY-01 and TASK-01"

  - name: PLAY-01 and TASK-02
    ansible.builtin.debug:
     msg: "hello from PLAY-01 and TASK-02"


- name: PLAY-02
  hosts: frontend
  tasks:
  - name: PLAY-02 and TASK-02
    ansible.builtin.debug:
     msg: "hello from PLAY-02 and TASK-02"

  - name: PLAY-02 and TASK-03
    ansible.builtin.debug:
     msg: "hello from PLAY-02 and TASK-03"

- name: PLAY-03
  hosts: frontend
  tasks:
  - name: PLAY-03 and TASK-04
    ansible.builtin.debug:
     msg: "hello from PLAY-03 and TASK-04"

  - name: PLAY-03 and TASK-04
    ansible.builtin.debug:
     msg: "hello from PLAY-03 and TASK-04"     